### ISSUE TITLE
[feature] Make the github-wiki repository readable

### ISSUE THREAD

**Issue by NobbZ** [locriani/magmawiki#2]
Since the github-wiki will be in a git repo in the future (end of september is planned to convert all) it would be a nice feature for magmawiki if we could load that repository into a magmawiki and save it back as a repository afterwards.

Other cool depending features are left to a cron job :D

**Comment by epitron** [comment]
I see two problems with this:
1) Painful!
2) People would be viewing the github wiki instead of a magmawiki!

**Comment by NobbZ** [comment]
No, the Magmawiki is much more beautiful :D
But I can understand number 1!

**Comment by locriani** [comment]
I'm slightly confused, describe this in a bit more detail for me!

**Comment by epitron** [comment]
It sounds like github will have some kind of standard for shoving a series of wiki revisions into a git repo, thus allowing you to edit your wiki offline and push it into the repository.

It _sounds_ like it could be interesting, but it also sounds painful to do the conversion forwards/backwards from a database-backed wiki.

**Comment by NobbZ** [comment]
You can read more about the github-git-repo-wiki here: http://github.com/blog/699-making-github-more-open-git-backed-wikis

**Comment by epitron** [comment]
Ooo, their markup library is neat: http://github.com/github/markup
I really like the look of this emacs organizer language too: http://orgmode.org/

**Comment by epitron** [comment]
So, the problem with using GIT as a wiki storage is that the smallest unit in a diff is a line. Which is fine for a programming language, but in a wiki, there is no idea of a line.

There are characters, words, sentences, paragraphs, sections... but no lines!

The wiki storage/diffing engine was going to store the edits so that people could comment on them, and you could display adds/removes and stuff. Maybe even one of those cool timelines where you can scrub a slider and see the changes animate in realtime.
